apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lanOrganiser
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`lanOrganiser.local`)
    kind: Rule
    services:
    - name: lanOrganiser
      port: 8081